@startuml 一店多号

(*) --> "用户进入生意通"
if "是否有自建商品？" then
--> [true] "商家"
  if "所选时间段是否有授权关系？" then
  partition 新增视角 #LightGreen  {
    --> [true] 多号商家视角
  }
  else
  --> [false] 普通商家视角
  endif
else
--> [false] "达人"
  if "是否为某个商家的授权号？" then
  partition 新增视角 #LightGreen  {
    --> [true] 授权号视角
  }
  else
    --> [false] 普通达人视角
endif

多号商家视角 -right-> [可以查看] 授权号视角

多号商家视角 --> 分销他人
授权号视角 --> 分销他人
普通达人视角 --> 分销他人
普通商家视角 --> 分销他人

多号商家视角 --> 自建商品自卖
普通商家视角 --> 自建商品自卖

多号商家视角 --> 自建商品被分销
普通商家视角 --> 自建商品被分销

多号商家视角 --> 售卖三方商品
授权号视角 --> 售卖三方商品
普通达人视角 --> 售卖三方商品
普通商家视角 --> 售卖三方商品

授权号视角 --> 授权售卖

多号商家视角 --> 自建商品被授权售卖


@enduml